<StoreInfo
              telefone={mockConfiguracoes.telefone}
              horarioFuncionamentoInicio={mockConfiguracoes.horario_funcionamento_inicio}
              horarioFuncionamentoFim={mockConfiguracoes.horario_funcionamento_fim}
              meiosPagamento={mockConfiguracoes.meios_pagamento}
              entrega={mockConfiguracoes.entrega}
              taxaEntrega={mockConfiguracoes.taxa_entrega}
              emFerias={mockConfiguracoes.em_ferias}
            />